#!/bin/bash

echo "========================================="
echo "推送代码到 GitHub 仓库"
echo "========================================="
echo ""
echo "仓库: https://github.com/maning711/cassandra-rust-client"
echo ""
echo "请执行以下命令："
echo ""
echo "cd /Users/maning/cassandra-rust-client"
echo "git push -u origin main"
echo ""
echo "========================================="
echo "如果提示需要认证，你有以下选项："
echo "========================================="
echo ""
echo "选项 1: 使用 Personal Access Token (推荐)"
echo "  1. 访问: https://github.com/settings/tokens"
echo "  2. 点击 'Generate new token' -> 'Generate new token (classic)'"
echo "  3. 勾选 'repo' 权限"
echo "  4. 生成并复制 token"
echo "  5. 在 Username 提示时输入: maning711"
echo "  6. 在 Password 提示时粘贴: 你的 token"
echo ""
echo "选项 2: 配置 SSH 密钥"
echo "  1. 生成 SSH 密钥: ssh-keygen -t ed25519 -C '277943578@qq.com'"
echo "  2. 复制公钥: cat ~/.ssh/id_ed25519.pub"
echo "  3. 访问: https://github.com/settings/keys"
echo "  4. 添加新的 SSH 密钥"
echo "  5. 修改远程地址: git remote set-url origin git@github.com:maning711/cassandra-rust-client.git"
echo "  6. 推送: git push -u origin main"
echo ""
echo "选项 3: 使用 GitHub CLI"
echo "  brew install gh"
echo "  gh auth login"
echo "  git push -u origin main"
echo ""
